export const Menu = [
    {
        title: "Basic Components",
        items: [
            { name: "Quick Start", href: "/docs/quick-start" },
            { name: "Accordion", href: "/docs/accordion" },
            { name: "Avatar", href: "/docs/avatar" },
            { name: "Alerts", href: "/docs/alerts" },
            { name: "Badge", href: "/docs/badge" },
            { name: "Button", href: "/docs/button" },
            { name: "Card", href: "/docs/card" },
            { name: "Divider", href: "/docs/divider" },
            { name: "KBD (Keyboard Shortcut)", href: "/docs/kbd" },
            { name: "List Group", href: "/docs/list-group" },
            { name: "Popover", href: "/docs/popover" },
            { name: "Progress Bar", href: "/docs/progress-bar" },
            { name: "Spinner", href: "/docs/spinner" },
            { name: "Skeleton Loader", href: "/docs/skeleton-loader" },
            { name: "Table", href: "/docs/table" },
            { name: "Toast", href: "/docs/toast" },
            { name: "Tooltip", href: "/docs/tooltip" },
            { name: "Input Field", href: "/docs/input-field" },
            { name: "File Input", href: "/docs/file-input" },
            { name: "Textarea", href: "/docs/textarea" },
            { name: "Select Dropdown", href: "/docs/select" },
            { name: "Checkbox", href: "/docs/checkbox" },
            { name: "Radio", href: "/docs/radio" },
            { name: "Range Slider", href: "/docs/slider" },
            { name: "Toggle Switch", href: "/docs/toggle-switch" },
            { name: "Color Picker", href: "/docs/color-picker" },
            { name: "Stepper", href: "/docs/stepper" },
            { name: "Breadcrumbs", href: "/docs/breadcrumbs" },
            { name: "Pagination", href: "/docs/pagination" },
            { name: "Stats Card", href: "/docs/stats-card" },
            { name: "Rating", href: "/docs/rating" },
            { name: "Gallery", href: "/docs/gallery" },
            { name: "About Page", href: "/docs/about-page" },
            { name: "Coming Soon Page", href: "/docs/coming-soon" },
            { name: "Contact Form", href: "/docs/contact-form" },
            { name: "CTA Section", href: "/docs/cta-section" },
            { name: "FAQ Section", href: "/docs/faq-section" },
            { name: "Footer", href: "/docs/footer" },
            { name: "Hero Section", href: "/docs/hero-section" },
            { name: "Landing Page", href: "/docs/landing-page" },
            { name: "Login Page", href: "/docs/login" },
            { name: "Maintenance Page", href: "/docs/maintenance" },
            { name: "Newsletter Signup", href: "/docs/newsletter-signup" },
            { name: "Pricing Page", href: "/docs/pricing" },
            { name: "Register Page", href: "/docs/register" },
            { name: "Team Section", href: "/docs/team-section" },
            { name: "Testimonial Section", href: "/docs/testimonials" },
            { name: "404 Page", href: "/docs/404-page" },
        ],
    },
];
